version: '3'

services:
    backend:
      image: backend1
      container_name: backend1
      ports:
        - 8080:8080
        
        
    frontend:
      image: frontend1
      container_name: frontend1
      ports:
        - 5000:5000